/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.14.0
// source: service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as service_pb from './service_pb';


export class MetaServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorList = new grpcWeb.MethodDescriptor(
    '/MetaService/List',
    grpcWeb.MethodType.UNARY,
    service_pb.MetaListRequest,
    service_pb.MetaListResponse,
    (request: service_pb.MetaListRequest) => {
      return request.serializeBinary();
    },
    service_pb.MetaListResponse.deserializeBinary
  );

  list(
    request: service_pb.MetaListRequest,
    metadata: grpcWeb.Metadata | null): Promise<service_pb.MetaListResponse>;

  list(
    request: service_pb.MetaListRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.MetaListResponse) => void): grpcWeb.ClientReadableStream<service_pb.MetaListResponse>;

  list(
    request: service_pb.MetaListRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.MetaListResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/MetaService/List',
        request,
        metadata || {},
        this.methodDescriptorList,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/MetaService/List',
    request,
    metadata || {},
    this.methodDescriptorList);
  }

  methodDescriptorGet = new grpcWeb.MethodDescriptor(
    '/MetaService/Get',
    grpcWeb.MethodType.UNARY,
    service_pb.MetaGetRequest,
    service_pb.MetaGetResponse,
    (request: service_pb.MetaGetRequest) => {
      return request.serializeBinary();
    },
    service_pb.MetaGetResponse.deserializeBinary
  );

  get(
    request: service_pb.MetaGetRequest,
    metadata: grpcWeb.Metadata | null): Promise<service_pb.MetaGetResponse>;

  get(
    request: service_pb.MetaGetRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.MetaGetResponse) => void): grpcWeb.ClientReadableStream<service_pb.MetaGetResponse>;

  get(
    request: service_pb.MetaGetRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.MetaGetResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/MetaService/Get',
        request,
        metadata || {},
        this.methodDescriptorGet,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/MetaService/Get',
    request,
    metadata || {},
    this.methodDescriptorGet);
  }

  methodDescriptorSetFavorite = new grpcWeb.MethodDescriptor(
    '/MetaService/SetFavorite',
    grpcWeb.MethodType.UNARY,
    service_pb.SetFavoriteRequest,
    service_pb.SetFavoriteResponse,
    (request: service_pb.SetFavoriteRequest) => {
      return request.serializeBinary();
    },
    service_pb.SetFavoriteResponse.deserializeBinary
  );

  setFavorite(
    request: service_pb.SetFavoriteRequest,
    metadata: grpcWeb.Metadata | null): Promise<service_pb.SetFavoriteResponse>;

  setFavorite(
    request: service_pb.SetFavoriteRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.SetFavoriteResponse) => void): grpcWeb.ClientReadableStream<service_pb.SetFavoriteResponse>;

  setFavorite(
    request: service_pb.SetFavoriteRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.SetFavoriteResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/MetaService/SetFavorite',
        request,
        metadata || {},
        this.methodDescriptorSetFavorite,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/MetaService/SetFavorite',
    request,
    metadata || {},
    this.methodDescriptorSetFavorite);
  }

  methodDescriptorGetPage = new grpcWeb.MethodDescriptor(
    '/MetaService/GetPage',
    grpcWeb.MethodType.UNARY,
    service_pb.GetPageRequest,
    service_pb.GetPageResponse,
    (request: service_pb.GetPageRequest) => {
      return request.serializeBinary();
    },
    service_pb.GetPageResponse.deserializeBinary
  );

  getPage(
    request: service_pb.GetPageRequest,
    metadata: grpcWeb.Metadata | null): Promise<service_pb.GetPageResponse>;

  getPage(
    request: service_pb.GetPageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.GetPageResponse) => void): grpcWeb.ClientReadableStream<service_pb.GetPageResponse>;

  getPage(
    request: service_pb.GetPageRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.GetPageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/MetaService/GetPage',
        request,
        metadata || {},
        this.methodDescriptorGetPage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/MetaService/GetPage',
    request,
    metadata || {},
    this.methodDescriptorGetPage);
  }

}

export class TagServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorList = new grpcWeb.MethodDescriptor(
    '/TagService/List',
    grpcWeb.MethodType.UNARY,
    service_pb.TagListRequest,
    service_pb.TagListResponse,
    (request: service_pb.TagListRequest) => {
      return request.serializeBinary();
    },
    service_pb.TagListResponse.deserializeBinary
  );

  list(
    request: service_pb.TagListRequest,
    metadata: grpcWeb.Metadata | null): Promise<service_pb.TagListResponse>;

  list(
    request: service_pb.TagListRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.TagListResponse) => void): grpcWeb.ClientReadableStream<service_pb.TagListResponse>;

  list(
    request: service_pb.TagListRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.TagListResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/TagService/List',
        request,
        metadata || {},
        this.methodDescriptorList,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/TagService/List',
    request,
    metadata || {},
    this.methodDescriptorList);
  }

  methodDescriptorSetFavorite = new grpcWeb.MethodDescriptor(
    '/TagService/SetFavorite',
    grpcWeb.MethodType.UNARY,
    service_pb.SetFavoriteRequest,
    service_pb.SetFavoriteResponse,
    (request: service_pb.SetFavoriteRequest) => {
      return request.serializeBinary();
    },
    service_pb.SetFavoriteResponse.deserializeBinary
  );

  setFavorite(
    request: service_pb.SetFavoriteRequest,
    metadata: grpcWeb.Metadata | null): Promise<service_pb.SetFavoriteResponse>;

  setFavorite(
    request: service_pb.SetFavoriteRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.SetFavoriteResponse) => void): grpcWeb.ClientReadableStream<service_pb.SetFavoriteResponse>;

  setFavorite(
    request: service_pb.SetFavoriteRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.SetFavoriteResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/TagService/SetFavorite',
        request,
        metadata || {},
        this.methodDescriptorSetFavorite,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/TagService/SetFavorite',
    request,
    metadata || {},
    this.methodDescriptorSetFavorite);
  }

}

